runtime: python39
entrypoint: serve -s .
handlers:
  - url: /style.css
    static_files: Assets/styles.css
    upload: Assets/styles.css
  - url: /.*
    static_files: index.html
    upload: index.html